### ISSUE TITLE
Bitte alle Files re-formatieren (Ctrl + Alt + L)

### ISSUE THREAD

**Issue by Oliver-was-taken** [leorott/GradesPlus#2]
Ich bechum en schlagafall wenni die Files aluege

**Comment by Oliver-was-taken** [comment]
spass aber bitte reformatiere

**Comment by leorott** [comment]
ich bechum en schlagafall wenni diis profilbild gsehn 😉

**Comment by leorott** [comment]
spass wird natürlich gefixt

**Comment by Oliver-was-taken** [comment]
sorry D:
ich machs nümm
